name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install gpg
      run: brew install gnupg
    - name: Setup provisioning profile
      env: 
        IOS_KEYS: ${{ secrets.IOS_KEYS }}
      run: ./.github/secrets/decrypt_secrets.sh
    - name: Build
      run: xcodebuild build -workspace 'Apple Pie.xcodeproj/project.xcworkspace' -scheme 'Apple Pie' -allowProvisioningUpdates PROVISIONING_PROFILE="de0f3ccb-8573-48b0-bc96-f57442a97ac5"
 
